# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgPr2dIKQ3pJCyr8MfpScvKqocwtCfOM
"""

# ============================================================
# 🚀 Migración SQLite → DuckDB robusta (corregido fotos_descargadas)
# ============================================================

!pip install duckdb tqdm

import duckdb
import sqlite3
import os
from tqdm import tqdm
from google.colab import drive

# 1️⃣ Montar Drive
drive.mount('/content/drive')

# 2️⃣ Rutas SQLite
rutas_sqlite = [
    "/content/drive/MyDrive/Backup BD/correos(2).db",
    "/content/drive/MyDrive/Backup BD/correos(3).db",
    "/content/drive/MyDrive/Backup BD/imagenes_telegram.db"
]

# 3️⃣ Ruta DuckDB final
ruta_duckdb = "/content/drive/MyDrive/Backup BD/proyectocv.duckdb"

# 4️⃣ Conectar DuckDB
conn_duck = duckdb.connect(ruta_duckdb)

# 5️⃣ Crear tablas
conn_duck.execute("""
CREATE TABLE IF NOT EXISTS correos (
    id BIGINT PRIMARY KEY,
    correo TEXT UNIQUE,
    enviado TEXT DEFAULT 'no'
)
""")

conn_duck.execute("""
CREATE TABLE IF NOT EXISTS telefonos (
    id BIGINT PRIMARY KEY,
    telefono TEXT UNIQUE,
    enviado TEXT DEFAULT 'no'
)
""")

conn_duck.execute("""
CREATE TABLE IF NOT EXISTS fotos_descargadas (
    chat_id BIGINT,
    message_id BIGINT,
    file_path TEXT,
    PRIMARY KEY(chat_id, message_id)
)
""")

# 6️⃣ Contador de IDs
next_id = {
    "correos": 1,
    "telefonos": 1
}

# 7️⃣ Función de migración
def migrar_sqlite_a_duck(sqlite_path, tabla, columnas, unique_col=None):
    global next_id
    if not os.path.exists(sqlite_path):
        print(f"⚠️ Archivo no encontrado: {sqlite_path}")
        return

    conn_sql = sqlite3.connect(sqlite_path)
    cursor_sql = conn_sql.cursor()

    cursor_sql.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tablas = [t[0] for t in cursor_sql.fetchall()]
    if tabla not in tablas:
        conn_sql.close()
        return

    # Extraer filas
    cursor_sql.execute(f"SELECT {', '.join(columnas)} FROM {tabla}")
    filas = cursor_sql.fetchall()

    if filas:
        for fila in filas:
            # ✅ Solo generamos ID para correos y telefonos
            if tabla in ["correos", "telefonos"]:
                id_val = next_id[tabla]
                next_id[tabla] += 1
                cols = ["id"] + columnas
                placeholders = ','.join(['?']*(len(fila)+1))
                values = [id_val]+list(fila)
            else:
                cols = columnas
                placeholders = ','.join(['?']*len(fila))
                values = list(fila)

            # SQL con ON CONFLICT si hay columna única
            if unique_col:
                sql = f"""
                INSERT INTO {tabla} ({', '.join(cols)})
                VALUES ({placeholders})
                ON CONFLICT({unique_col}) DO NOTHING
                """
            else:
                sql = f"""
                INSERT OR IGNORE INTO {tabla} ({', '.join(cols)}) VALUES ({placeholders})
                """

            conn_duck.execute(sql, values)

        print(f"✅ Migradas {len(filas)} filas de {tabla} desde {os.path.basename(sqlite_path)}")

    conn_sql.close()

# 8️⃣ Migrar todas las bases
for ruta in rutas_sqlite:
    print(f"\n🔹 Procesando {os.path.basename(ruta)}")
    migrar_sqlite_a_duck(ruta, "correos", ["correo", "enviado"], unique_col="correo")
    migrar_sqlite_a_duck(ruta, "telefonos", ["telefono", "enviado"], unique_col="telefono")
    migrar_sqlite_a_duck(ruta, "fotos_descargadas", ["chat_id", "message_id", "file_path"])

# 9️⃣ Cerrar DuckDB
conn_duck.close()

print("\n🎯 Migración completada correctamente!")
print(f"📌 Base unificada en: {ruta_duckdb}")

import duckdb
from google.colab import drive

drive.mount('/content/drive')

ruta_duckdb = "/content/drive/MyDrive/Backup BD/proyectocv.duckdb"
conn = duckdb.connect(ruta_duckdb)

# Listar todas las tablas de la base
tablas = conn.execute("SHOW TABLES").fetchall()
print("📚 Tablas existentes en la DuckDB:")
for t in tablas:
    print(" -", t[0])

conn.close()

import os

ruta_duckdb = "/content/drive/MyDrive/Backup BD/proyectocv.duckdb"
print("Archivo existe:", os.path.exists(ruta_duckdb))
print("Tamaño del archivo (bytes):", os.path.getsize(ruta_duckdb))

# ============================================================
# 🚀 Migración SQLite → DuckDB robusta (corregido fotos_descargadas)
# ============================================================

!pip install duckdb tqdm

import duckdb
import sqlite3
import os
from tqdm import tqdm
from google.colab import drive

# 1️⃣ Montar Drive
drive.mount('/content/drive')

# 2️⃣ Rutas SQLite
rutas_sqlite = [
    "/content/drive/MyDrive/Backup BD/correos(2).db",
    "/content/drive/MyDrive/Backup BD/correos(3).db",
    "/content/drive/MyDrive/Backup BD/imagenes_telegram.db"
]

# 3️⃣ Ruta DuckDB final
ruta_duckdb = "/content/drive/MyDrive/Backup BD/proyectocv.duckdb"

# 4️⃣ Conectar DuckDB
conn_duck = duckdb.connect(ruta_duckdb)

# 5️⃣ Crear tablas
conn_duck.execute("""
CREATE TABLE IF NOT EXISTS correos (
    id BIGINT PRIMARY KEY,
    correo TEXT UNIQUE,
    enviado TEXT DEFAULT 'no'
)
""")

conn_duck.execute("""
CREATE TABLE IF NOT EXISTS telefonos (
    id BIGINT PRIMARY KEY,
    telefono TEXT UNIQUE,
    enviado TEXT DEFAULT 'no'
)
""")

conn_duck.execute("""
CREATE TABLE IF NOT EXISTS fotos_descargadas (
    chat_id BIGINT,
    message_id BIGINT,
    file_path TEXT,
    PRIMARY KEY(chat_id, message_id)
)
""")

# 6️⃣ Contador de IDs
next_id = {
    "correos": 1,
    "telefonos": 1
}

# 7️⃣ Función de migración
def migrar_sqlite_a_duck(sqlite_path, tabla, columnas, unique_col=None):
    global next_id
    if not os.path.exists(sqlite_path):
        print(f"⚠️ Archivo no encontrado: {sqlite_path}")
        return

    conn_sql = sqlite3.connect(sqlite_path)
    cursor_sql = conn_sql.cursor()

    # Revisar si existe la tabla
    cursor_sql.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tablas = [t[0] for t in cursor_sql.fetchall()]
    if tabla not in tablas:
        conn_sql.close()
        return

    # Extraer filas
    cursor_sql.execute(f"SELECT {', '.join(columnas)} FROM {tabla}")
    filas = cursor_sql.fetchall()

    if filas:
        for fila in filas:
            # Generar ID para correos y telefonos
            if tabla in ["correos", "telefonos"]:
                id_val = next_id[tabla]
                next_id[tabla] += 1
                cols = ["id"] + columnas
                values = [id_val] + list(fila)
            else:
                cols = columnas
                values = list(fila)

            # Insertar con manejo de duplicados
            if tabla in ["correos", "telefonos"]:
                # DuckDB soporta INSERT ... ON CONFLICT en columnas UNIQUE
                sql = f"""
                INSERT INTO {tabla} ({', '.join(cols)})
                SELECT {', '.join(['?']*len(values))}
                WHERE NOT EXISTS (SELECT 1 FROM {tabla} WHERE {unique_col}=?)
                """
                conn_duck.execute(sql, values + [values[1]])  # valor único al final
            else:
                # fotos_descargadas: clave primaria compuesta
                sql = f"""
                INSERT INTO {tabla} ({', '.join(cols)})
                SELECT {', '.join(['?']*len(values))}
                WHERE NOT EXISTS (SELECT 1 FROM {tabla} WHERE chat_id=? AND message_id=?)
                """
                conn_duck.execute(sql, values + [values[0], values[1]])

        print(f"✅ Migradas {len(filas)} filas de {tabla} desde {os.path.basename(sqlite_path)}")

    conn_sql.close()

# 8️⃣ Migrar todas las bases
for ruta in rutas_sqlite:
    print(f"\n🔹 Procesando {os.path.basename(ruta)}")
    migrar_sqlite_a_duck(ruta, "correos", ["correo", "enviado"], unique_col="correo")
    migrar_sqlite_a_duck(ruta, "telefonos", ["telefono", "enviado"], unique_col="telefono")
    migrar_sqlite_a_duck(ruta, "fotos_descargadas", ["chat_id", "message_id", "file_path"])

# 9️⃣ Guardar cambios y cerrar DuckDB
conn_duck.execute("COMMIT")
conn_duck.close()

print("\n🎯 Migración completada correctamente!")
print(f"📌 Base unificada en: {ruta_duckdb}")

# ============================================================
# 🚀 Migración SQLite → DuckDB simple y funcional
# ============================================================

!pip install duckdb tqdm

import duckdb
import sqlite3
import os
from tqdm import tqdm
from google.colab import drive

# 1️⃣ Montar Drive
drive.mount('/content/drive')

# 2️⃣ Rutas SQLite
rutas_sqlite = [
    "/content/drive/MyDrive/Backup BD/correos(2).db",
    "/content/drive/MyDrive/Backup BD/correos(3).db",
    "/content/drive/MyDrive/Backup BD/imagenes_telegram.db"
]

# 3️⃣ Ruta DuckDB final
ruta_duckdb = "/content/drive/MyDrive/Backup BD/proyectocv.duckdb"

# 4️⃣ Conectar DuckDB
conn_duck = duckdb.connect(ruta_duckdb)

# 5️⃣ Crear tablas básicas
conn_duck.execute("""
CREATE TABLE IF NOT EXISTS correos (
    correo TEXT UNIQUE,
    enviado TEXT DEFAULT 'no'
)
""")

conn_duck.execute("""
CREATE TABLE IF NOT EXISTS telefonos (
    telefono TEXT UNIQUE,
    enviado TEXT DEFAULT 'no'
)
""")

conn_duck.execute("""
CREATE TABLE IF NOT EXISTS fotos_descargadas (
    chat_id BIGINT,
    message_id BIGINT,
    file_path TEXT,
    PRIMARY KEY(chat_id, message_id)
)
""")

# 6️⃣ Función de migración simplificada
def migrar_sqlite_a_duck_simple(sqlite_path, tabla, columnas, unique_col=None):
    if not os.path.exists(sqlite_path):
        print(f"⚠️ Archivo no encontrado: {sqlite_path}")
        return

    conn_sql = sqlite3.connect(sqlite_path)
    cursor_sql = conn_sql.cursor()

    # Verificar que la tabla exista
    cursor_sql.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tablas = [t[0] for t in cursor_sql.fetchall()]
    if tabla not in tablas:
        conn_sql.close()
        return

    # Extraer filas
    cursor_sql.execute(f"SELECT {', '.join(columnas)} FROM {tabla}")
    filas = cursor_sql.fetchall()

    if filas:
        for fila in filas:
            # Insertar solo si no existe
            if tabla in ["correos", "telefonos"] and unique_col:
                sql = f"""
                INSERT INTO {tabla} ({', '.join(columnas)})
                SELECT {', '.join(['?']*len(fila))}
                WHERE NOT EXISTS (
                    SELECT 1 FROM {tabla} WHERE {unique_col}=?
                )
                """
                conn_duck.execute(sql, list(fila) + [fila[0]])
            elif tabla == "fotos_descargadas":
                sql = f"""
                INSERT INTO {tabla} ({', '.join(columnas)})
                SELECT {', '.join(['?']*len(fila))}
                WHERE NOT EXISTS (
                    SELECT 1 FROM {tabla} WHERE chat_id=? AND message_id=?
                )
                """
                conn_duck.execute(sql, list(fila) + [fila[0], fila[1]])

        print(f"✅ Migradas {len(filas)} filas de {tabla} desde {os.path.basename(sqlite_path)}")

    conn_sql.close()

# 7️⃣ Migrar todas las bases
for ruta in rutas_sqlite:
    print(f"\n🔹 Procesando {os.path.basename(ruta)}")
    migrar_sqlite_a_duck_simple(ruta, "correos", ["correo", "enviado"], unique_col="correo")
    migrar_sqlite_a_duck_simple(ruta, "telefonos", ["telefono", "enviado"], unique_col="telefono")
    migrar_sqlite_a_duck_simple(ruta, "fotos_descargadas", ["chat_id", "message_id", "file_path"])

# 8️⃣ Cerrar DuckDB
conn_duck.close()

print("\n🎯 Migración completada correctamente!")
print(f"📌 Base unificada en: {ruta_duckdb}")

# ============================================================
# 📊 Auditoría completa DuckDB - proyectocv.duckdb
# ============================================================

import duckdb
from google.colab import drive
drive.mount('/content/drive')

# Ruta de la base unificada
ruta_duckdb = "/content/drive/MyDrive/Backup BD/proyectocv.duckdb"

# Conectar DuckDB
conn = duckdb.connect(ruta_duckdb)

# 1️⃣ Listar tablas existentes
tablas = conn.execute("SHOW TABLES").fetchall()
print("📚 Tablas en la base DuckDB:")
for t in tablas:
    print(" -", t[0])

# 2️⃣ Auditoría de correos
total_correos = conn.execute('SELECT COUNT(*) FROM correos').fetchone()[0]
enviados_correos = conn.execute("SELECT COUNT(*) FROM correos WHERE enviado='sí'").fetchone()[0]
pendientes_correos = total_correos - enviados_correos

print("\n📊 ESTADO GENERAL DE CORREOS")
print(f"Total correos      : {total_correos}")
print(f"Correos enviados   : {enviados_correos}")
print(f"Correos pendientes : {pendientes_correos}")
print(f"Progreso           : {enviados_correos/total_correos*100:.2f}%")

# Últimos 10 correos
print("\n📤 Últimos 10 correos:")
ultimos_correos = conn.execute("SELECT correo, enviado FROM correos ORDER BY correo DESC LIMIT 10").fetchall()
for c in ultimos_correos:
    print(" -", c)

# 3️⃣ Auditoría de teléfonos
total_tel = conn.execute("SELECT COUNT(*) FROM telefonos").fetchone()[0]
enviados_tel = conn.execute("SELECT COUNT(*) FROM telefonos WHERE enviado='sí'").fetchone()[0]
pendientes_tel = total_tel - enviados_tel

print("\n📊 ESTADO GENERAL DE TELÉFONOS")
print(f"Total teléfonos    : {total_tel}")
print(f"Teléfonos enviados : {enviados_tel}")
print(f"Teléfonos pendientes: {pendientes_tel}")
print(f"Progreso           : {enviados_tel/total_tel*100:.2f}%")

# Últimos 10 teléfonos
print("\n📤 Últimos 10 teléfonos:")
ultimos_tel = conn.execute("SELECT telefono, enviado FROM telefonos ORDER BY telefono DESC LIMIT 10").fetchall()
for t in ultimos_tel:
    print(" -", t)

# 4️⃣ Auditoría fotos descargadas
total_fotos = conn.execute("SELECT COUNT(*) FROM fotos_descargadas").fetchone()[0]
print("\n📊 ESTADO GENERAL DE FOTOS DESCARGADAS")
print(f"Total fotos guardadas: {total_fotos}")

# Últimas 10 fotos
print("\n📤 Últimas 10 fotos descargadas:")
ultimas_fotos = conn.execute("SELECT chat_id, message_id, file_path FROM fotos_descargadas ORDER BY message_id DESC LIMIT 10").fetchall()
for f in ultimas_fotos:
    print(" -", f)

# Cerrar conexión
conn.close()
print("\n✅ Auditoría finalizada correctamente")

# ============================================================
# 📊 Auditoría completa DuckDB con estructura de tablas
# ============================================================

import duckdb
from google.colab import drive

# 1️⃣ Montar Drive
drive.mount('/content/drive')

# 2️⃣ Conectar DuckDB
ruta_duckdb = "/content/drive/MyDrive/Backup BD/proyectocv.duckdb"
conn = duckdb.connect(ruta_duckdb)

# 3️⃣ Listar tablas
tablas = conn.execute("SHOW TABLES").fetchall()
tablas = [t[0] for t in tablas]
print("📚 Tablas en la base DuckDB:")
for t in tablas:
    print(" -", t)

# 4️⃣ Revisar estructura y contenido de cada tabla
for tabla in tablas:
    print(f"\n📝 Estructura de la tabla '{tabla}':")
    columnas = conn.execute(f"PRAGMA table_info('{tabla}')").fetchall()
    for col in columnas:
        cid, name, tipo, notnull, dflt_value, pk = col
        print(f"   - {name} | {tipo} | NOT NULL: {bool(notnull)} | PK: {bool(pk)} | DEFAULT: {dflt_value}")

    # 5️⃣ Totales de filas
    total_filas = conn.execute(f"SELECT COUNT(*) FROM {tabla}").fetchone()[0]
    print(f"   🔹 Total de filas: {total_filas}")

    # 6️⃣ Mostrar últimos 5 registros como ejemplo
    ultimos = conn.execute(f"SELECT * FROM {tabla} ORDER BY ROWID DESC LIMIT 5").fetchall()
    print("   🔹 Últimos registros:")
    for r in ultimos:
        print("     ", r)

# 7️⃣ Cerrar conexión
conn.close()
print("\n✅ Auditoría completa de estructura y contenido finalizada")